# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
	Pais.create(descripcion: 'Venezuela', codigo: 'VE',estatus: 1)
	Pais.create(descripcion: 'Mexico', codigo: 'MX',estatus: 1)
	Pais.create(descripcion: 'Antigua y Barbudas', codigo: 'AB',estatus: 1)
	Pais.create(descripcion: 'Bahamas', codigo: 'BH',estatus: 1)
	Pais.create(descripcion: 'Barbados', codigo: 'BA',estatus: 1)
	Pais.create(descripcion: 'Belice', codigo: 'BL',estatus: 1)
	Pais.create(descripcion: 'Costa Rica', codigo: 'CR',estatus: 1)
	Pais.create(descripcion: 'Cuba', codigo: 'CU',estatus: 1)
	Pais.create(descripcion: 'Dominica', codigo: 'DM',estatus: 1)
	Pais.create(descripcion: 'El Salvador', codigo: 'ES',estatus: 1)
	Pais.create(descripcion: 'Grenada', codigo: 'GR',estatus: 1)
	Pais.create(descripcion: 'Guatemala', codigo: 'GT',estatus: 1)
	Pais.create(descripcion: 'Haiti', codigo: 'HA',estatus: 1)
	Pais.create(descripcion: 'Honduras', codigo: 'HO',estatus: 1)
	Pais.create(descripcion: 'Jamaica', codigo: 'JA',estatus: 1)
	Pais.create(descripcion: 'Nicaragua', codigo: 'NC',estatus: 1)
	Pais.create(descripcion: 'Panama', codigo: 'PA',estatus: 1)
	Pais.create(descripcion: 'Puerto Rico', codigo: 'PR',estatus: 1)
	Pais.create(descripcion: 'Republica Dominicana', codigo: 'RD',estatus: 1)
	Pais.create(descripcion: 'Argentina', codigo: 'AR',estatus: 1)
	Pais.create(descripcion: 'Bolivia', codigo: 'BL',estatus: 1)
	Pais.create(descripcion: 'Brasil', codigo: 'BR',estatus: 1)
	Pais.create(descripcion: 'Chile', codigo: 'CH',estatus: 1)
	Pais.create(descripcion: 'Colombia', codigo: 'CO',estatus: 1)
	Pais.create(descripcion: 'Ecuador', codigo: 'EC',estatus: 1)
	Pais.create(descripcion: 'Uruguay', codigo: 'UR',estatus: 1)
	TipoHabito.create(descripcion: 'Fisicos',estatus: 1)
	TipoHabito.create(descripcion: 'Afectivos',estatus: 1)
	TipoHabito.create(descripcion: 'Sociales',estatus: 1)
	TipoHabito.create(descripcion: 'Morales',estatus: 1)
	TipoHabito.create(descripcion: 'Costumbristas',estatus: 1)
	TipoHabito.create(descripcion: 'Higiene',estatus: 1)
	TipoHabito.create(descripcion: 'Cognitivos',estatus: 1)
	TipoHabito.create(descripcion: 'Alimentacion',estatus: 1)
	Vacunas.create(descripcion: 'Fiebre Amarilla',estatus: 1)
	Vacunas.create(descripcion: 'Dengue',estatus: 1)
	Vacunas.create(descripcion: 'Sarampion',estatus: 1)
	Pregunta.create(descripcion: 'Como ha parecido el servicio?',estatus: 1)
	Pregunta.create(descripcion: 'Como ha sido la atencion?',estatus: 1)
	Pregunta.create(descripcion: 'Califique el tiempo de espera',estatus: 1)
	TipoPatologia.create(descripcion: 'Tumores',estatus: 1)
	TipoPatologia.create(descripcion: 'Quirurgica',estatus: 1)
	TipoPatologia.create(descripcion: 'Molecular',estatus: 1)
	TipoPatologia.create(descripcion: 'Dermatologica',estatus: 1)
	TipoPatologia.create(descripcion: 'Histopatologia',estatus: 1)
	Pais.create(descripcion: 'Venezuela', codigo: 'VE',estatus: 1)
	Pais.create(descripcion: 'Mexico', codigo: 'MX',estatus: 1)
	Pais.create(descripcion: 'Antigua y Barbudas', codigo: 'AB',estatus: 1)
	Pais.create(descripcion: 'Bahamas', codigo: 'BH',estatus: 1)
	Pais.create(descripcion: 'Barbados', codigo: 'BA',estatus: 1)
	Pais.create(descripcion: 'Belice', codigo: 'BL',estatus: 1)
	Pais.create(descripcion: 'Costa Rica', codigo: 'CR',estatus: 1)
	Pais.create(descripcion: 'Cuba', codigo: 'CU',estatus: 1)
	Pais.create(descripcion: 'Dominica', codigo: 'DM',estatus: 1)
	Pais.create(descripcion: 'El Salvador', codigo: 'ES',estatus: 1)
	Pais.create(descripcion: 'Grenada', codigo: 'GR',estatus: 1)
	Pais.create(descripcion: 'Guatemala', codigo: 'GT',estatus: 1)
	Pais.create(descripcion: 'Haiti', codigo: 'HA',estatus: 1)
	Pais.create(descripcion: 'Honduras', codigo: 'HO',estatus: 1)
	Pais.create(descripcion: 'Jamaica', codigo: 'JA',estatus: 1)
	Pais.create(descripcion: 'Nicaragua', codigo: 'NC',estatus: 1)
	Pais.create(descripcion: 'Panama', codigo: 'PA',estatus: 1)
	Pais.create(descripcion: 'Puerto Rico', codigo: 'PR',estatus: 1)
	Pais.create(descripcion: 'Republica Dominicana', codigo: 'RD',estatus: 1)
	Pais.create(descripcion: 'Argentina', codigo: 'AR',estatus: 1)
	Pais.create(descripcion: 'Bolivia', codigo: 'BL',estatus: 1)
	Pais.create(descripcion: 'Brasil', codigo: 'BR',estatus: 1)
	Pais.create(descripcion: 'Chile', codigo: 'CH',estatus: 1)
	Pais.create(descripcion: 'Colombia', codigo: 'CO',estatus: 1)
	Pais.create(descripcion: 'Ecuador', codigo: 'EC',estatus: 1)
	Pais.create(descripcion: 'Uruguay', codigo: 'UR',estatus: 1)
	TipoHabito.create(descripcion: 'Fisicos',estatus: 1)
	TipoHabito.create(descripcion: 'Afectivos',estatus: 1)
	TipoHabito.create(descripcion: 'Sociales',estatus: 1)
	TipoHabito.create(descripcion: 'Morales',estatus: 1)
	TipoHabito.create(descripcion: 'Costumbristas',estatus: 1)
	TipoHabito.create(descripcion: 'Higiene',estatus: 1)
	TipoHabito.create(descripcion: 'Cognitivos',estatus: 1)
	TipoHabito.create(descripcion: 'Alimentacion',estatus: 1)
	Vacunas.create(descripcion: 'Fiebre Amarilla',estatus: 1)
	Vacunas.create(descripcion: 'Dengue',estatus: 1)
	Vacunas.create(descripcion: 'Sarampion',estatus: 1)
	Pregunta.create(descripcion: 'Como ha parecido el servicio?',estatus: 1)
	Pregunta.create(descripcion: 'Como ha sido la atencion?',estatus: 1)
	Pregunta.create(descripcion: 'Califique el tiempo de espera',estatus: 1)
	TipoPatologia.create(descripcion: 'Tumores',estatus: 1)
	TipoPatologia.create(descripcion: 'Quirurgica',estatus: 1)
	TipoPatologia.create(descripcion: 'Molecular',estatus: 1)
	TipoPatologia.create(descripcion: 'Dermatologica',estatus: 1)
	TipoPatologia.create(descripcion: 'Histopatologia',estatus: 1)