class InsertOptionMenu < ActiveRecord::Migration[5.0]
def change

    OptionMenu.create(:id_padre => nil, :nombre => 'Configuración General',     :url_path => '#', :icono => 'fa-cogs'       ,      :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
      OptionMenu.create(:id_padre => 1,   :nombre => 'Datos de Servicios',                :url_path => '#', :icono => 'fa-edit',           :controlador => '', :accion => '', num_hijos: 9, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Paises',                   :url_path => 'paises', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Estados',                   :url_path => 'estados', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Ciudades',                   :url_path => 'ciudades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Tipos de Ubicación',                   :url_path => 'tipo_ubicaciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Ubicaciónes',                   :url_path => 'ubicaciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Especialidades',                   :url_path => 'especialidades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Tipos de Atención',                   :url_path => 'tipo_atenciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Tipos de Servicio',                   :url_path => 'tipo_servicios', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 2, :nombre => 'Tipos de Evento',                   :url_path => 'tipo_eventos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 1,   :nombre => 'Datos de Agendas y Citas',              :url_path => '#', :icono => 'fa-edit', :controlador => '', :accion => '', num_hijos: 14, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Dias',                   :url_path => '', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Turnos',                   :url_path => '', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Bloques',                   :url_path => '', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Horario',                   :url_path => '#', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Cita',                   :url_path => '', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Pago',                   :url_path => 'tipo_pagos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Motivo',                   :url_path => 'tipo_motivos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Motivos',                   :url_path => 'motivos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Eventualidad',                   :url_path => 'tipo_eventualidades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Eventualidades',                   :url_path => 'eventualidades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Calificacion',                   :url_path => 'tipo_calificaciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Calificaciones',                   :url_path => 'calificaciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Tipos de Criterio',                   :url_path => 'tipo_criterios', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 12, :nombre => 'Criterios',                   :url_path => 'criterios', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 1,   :nombre => 'Datos de Segmentacion',                   :url_path => '#', :icono => 'fa-edit',          :controlador => '', :accion => '', num_hijos: 18, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Sexos',                   :url_path => 'sexos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Hábito',                   :url_path => 'tipo_habitos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Hábitos',                   :url_path => 'habitos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Lesion',                   :url_path => 'tipo_lesiones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Lesiones',                   :url_path => 'lesiones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Profesiones',                   :url_path => 'profesiones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Ocupaciones',                   :url_path => 'ocupaciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Estados Civiles',                   :url_path => 'estado_civiles', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Cirugía',                   :url_path => 'tipo_cirugias', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Cirugías',                   :url_path => 'cirugias', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Grupos Sanguíneos',                   :url_path => 'grupos_sanguineos', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Adiccion',                   :url_path => 'tipo_adicciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Adicciones',                   :url_path => 'adicciones', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Vacunas',                   :url_path => 'vacunas', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Patologías',                   :url_path => 'tipo_patologias', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Patologías',                   :url_path => 'patologias', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Tipos de Discapacidad',                   :url_path => 'tipo_discapacidades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
              OptionMenu.create(:id_padre => 27, :nombre => 'Discapacidades',                   :url_path => 'discapacidades', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
    OptionMenu.create(:id_padre => nil, :nombre => 'Oferta y Eventos',          :url_path => '#', :icono => 'fa-calendar',         :controlador => '', :accion => '', num_hijos: 2, :estatus => 'A')

      OptionMenu.create(:id_padre => 46,   :nombre => 'Catalogo de Servicios',   :url_path => '#', :icono => 'fa-table',           :controlador => '', :accion => '', num_hijos: 2, :estatus => 'A')
        OptionMenu.create(:id_padre => 47,   :nombre => 'Servicios',             :url_path => 'servicios', :icono => 'fa-flask',            :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 47,   :nombre => 'Especialistas',         :url_path => 'especialistas', :icono => 'fa-user-md',          :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 46,   :nombre => 'Catalogo de Eventos',     :url_path => '#', :icono => 'fa-table',            :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
     
    OptionMenu.create(:id_padre => nil,   :nombre => 'Agenda',                  :url_path => '#', :icono => 'fa-calendar',         :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
      OptionMenu.create(:id_padre => 51,  :nombre => 'Gestionar',               :url_path => '#', :icono => 'fa-search',           :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 51,  :nombre => 'Horarios',                :url_path => '#', :icono => 'fa-clock-o',          :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 51,  :nombre => 'Eventualidades',          :url_path => '#', :icono => 'fa-exclamation-circle',           :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')


  	OptionMenu.create(:id_padre => nil, :nombre => 'Citas',                     :url_path => '#', :icono => 'fa-stethoscope',      :controlador => '', :accion => '', num_hijos: 4, :estatus => 'A')
    	OptionMenu.create(:id_padre => 55,   :nombre => 'Generar',              :url_path => '#', :icono => 'fa-plus',           :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 55,   :nombre => 'Gestionar',              :url_path => '#', :icono => 'fa-search',           :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')    	
    	OptionMenu.create(:id_padre => 55,   :nombre => 'Historial',              :url_path => '#', :icono => 'fa-history',          :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 55,   :nombre => 'Eventualidades',         :url_path => '#', :icono => 'fa-exclamation-circle',           :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')  	

    OptionMenu.create(:id_padre => nil,   :nombre => 'Servicio Medico',    :url_path => '#', :icono => 'fa-hospital-o', :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
      OptionMenu.create(:id_padre => 60,   :nombre => 'Registrar Paciente',    :url_path => '#', :icono => 'fa-id-card-o', :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
    	OptionMenu.create(:id_padre => 60,   :nombre => 'Evaluar Cita',    :url_path => '#', :icono => 'fa-star-half-full', :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 60, :nombre => 'Consultar Pacientes',               :url_path => '#', :icono => 'fa-heartbeat',        :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
   

    OptionMenu.create(:id_padre => nil, :nombre => 'Reportes',                  :url_path => '#', :icono => 'fa-bar-chart',        :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
      OptionMenu.create(:id_padre => 64, :nombre => 'Estructurados',                   :url_path => '#', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 64, :nombre => 'No Estructurados',                   :url_path => '#', :icono => '',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')  
      OptionMenu.create(:id_padre => 64, :nombre => 'Estadisticos',                   :url_path => '#', :icono => '',             :controlador => '', :accion => '', num_hijos: 4, :estatus => 'A')  
        OptionMenu.create(:id_padre => 67,  :nombre => 'Satisfaccion del Paciente', :url_path => '#', :icono => 'fa-file-text-o',      :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 67,  :nombre => 'Citas Concretadas',         :url_path => '#', :icono => 'fa-pie-chart',      :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 67,  :nombre => 'Efectos de Difusion',       :url_path => '#', :icono => 'fa-file-text-o',      :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 67,  :nombre => 'Eventualidades',            :url_path => '#', :icono => 'fa-file-text-o',      :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
    

    OptionMenu.create(:id_padre => nil, :nombre => 'Administracion',              :url_path => '#', :icono => 'fa-cog',              :controlador => '', :accion => '', num_hijos: 4, :estatus => 'A')
      OptionMenu.create(:id_padre => 72, :nombre => 'Sitio Web',              :url_path => '#', :icono => 'fa-cog',              :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
  	    OptionMenu.create(:id_padre => 73,  :nombre => 'Contenido',                       :url_path => '#', :icono => 'fa-at',               :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 73,  :nombre => 'Imagenes',                  :url_path => '#', :icono => 'fa-desktop',          :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
  	    OptionMenu.create(:id_padre => 73,  :nombre => 'Noticias',                  :url_path => '#', :icono => 'newspaper',          :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 72, :nombre => 'Seguridad Funcional',                   :url_path => '#', :icono => 'fa-users',             :controlador => '', :accion => '', num_hijos: 3, :estatus => 'A')
        OptionMenu.create(:id_padre => 77, :nombre => 'Usuarios',               :url_path => 'usuarios/edit', :icono => 'fa-user-plus',        :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 77, :nombre => 'Roles',                      :url_path => 'roles', :icono => 'fa-bookmark-o',        :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
        OptionMenu.create(:id_padre => 77, :nombre => 'Permisos',                   :url_path => '#', :icono => 'fa-check',            :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 72, :nombre => 'General',                   :url_path => '#', :icono => 'fa-users',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
      OptionMenu.create(:id_padre => 72, :nombre => 'Base de Datos',                   :url_path => '#', :icono => 'fa-users',             :controlador => '', :accion => '', num_hijos: 0, :estatus => 'A')
    end
end
