# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/



$ ->
  table = $('#servicios-table').DataTable
    processing: true
    serverSide: true
    ajax: $('#servicios-table').data('source')
    pagingType: 'full_numbers'
    columns: [
      {
        data: "0"
      }
      {
        data: "1"
      }
      {
        "targets": -1
        "data": null
        "defaultContent": "<button class='btn btn-ver-agenda btn-primary'>Ver agenda</button>"
        "orderable": false
      }
    ]
  console.log(table)
  $('#servicios-table tbody').on 'click', 'button', ->
    row = table.row($(this).parents('tr'))
    window.open(row.data()[3], '_self')
    return
  return

# optional, if you want full pagination controls.
# Check dataTables documentation to learn more about
# available options


$(document).ready ->
  calendar = $('#calendar')
  calendar.fullCalendar
    header:
      left: 'prev,next today'
      center: 'title'
      right: 'listDay,listWeek,month'
    views:
      listDay:
        buttonText: 'Este día'
      listWeek:
        buttonText: 'Esta semana'
      month:
        buttonText: 'Este mes'
    defaultView: 'listWeek'
    locale: 'es'
    navLinks: true
    editable: true
    eventLimit: true
    events: calendar.data('source')
    eventClick: (event, jsEvent, v) =>
      if event.tipo == 'cita'
        alert "Paciente: #{event.title}\nCédula: #{event.cedula_persona}\nTipo de cita: #{event.tipo}\nEventualidad: #{event.eventualidad}"
      else if event.tipo == 'evento'
        alert "Evento: #{event.title}"
      else
        alert event.title
      return
  return

# ---
# generated by js2coffee 2.2.0