# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/



$ ->
  table = $('#servicios-table').DataTable
    processing: true
    serverSide: true
    ajax: $('#servicios-table').data('source')
    pagingType: 'full_numbers'
    columns: [
      {
        data: "0"
      }
      {
        data: "1"
      }
      {
        "targets": -1
        "data": null
        "defaultContent": "<button class='btn btn-ver-agenda btn-primary'>Ver agenda</button>"
        "orderable":      false
      }
    ]
  console.log(table)
  $('#servicios-table tbody').on 'click', 'button', ->
    row = table.row($(this).parents('tr'))

    window.open(row.id() + '/detalle', '_self')
    return
  return

# optional, if you want full pagination controls.
# Check dataTables documentation to learn more about
# available options


$(document).ready ->
  $('#calendar').fullCalendar
    header:
      left: 'prev,next today'
      center: 'title'
      right: 'listDay,listWeek,month'
    views:
      listDay: buttonText: 'list day'
      listWeek: buttonText: 'list week'
    defaultView: 'listWeek'
    defaultDate: '2017-02-12'
    navLinks: true
    editable: true
    eventLimit: true
    events: [
      {
        title: 'All Day Event'
        start: '2017-02-01'
      }
      {
        title: 'Long Event'
        start: '2017-02-07'
        end: '2017-02-10'
      }
      {
        id: 999
        title: 'Repeating Event'
        start: '2017-02-09T16:00:00'
      }
      {
        id: 999
        title: 'Repeating Event'
        start: '2017-02-16T16:00:00'
      }
      {
        title: 'Conference'
        start: '2017-02-11'
        end: '2017-02-13'
      }
      {
        title: 'Meeting'
        start: '2017-02-12T10:30:00'
        end: '2017-02-12T12:30:00'
      }
      {
        title: 'Lunch'
        start: '2017-02-12T12:00:00'
      }
      {
        title: 'Meeting'
        start: '2017-02-12T14:30:00'
      }
      {
        title: 'Happy Hour'
        start: '2017-02-12T17:30:00'
      }
      {
        title: 'Dinner'
        start: '2017-02-12T20:00:00'
      }
      {
        title: 'Birthday Party'
        start: '2017-02-13T07:00:00'
      }
      {
        title: 'Click for Google'
        url: 'http://google.com/'
        start: '2017-02-28'
      }
    ]
  return

# ---
# generated by js2coffee 2.2.0